sudo:
  - true
  - false

language:
  - c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      sudo: false
    - os: linux
      compiler: clang
    - os: linux
      sudo: true

addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - gcc-4.9
     - uuid-dev

install:
  - . .travis/install.sh
  - cd $TRAVIS_BUILD_DIR/..
  - export PACKAGES_PATH=$PWD
  - git clone --branch=development https://github.com/CupertinoNet/EfiMiscPkg.git
  - git clone --branch=development https://github.com/CupertinoNet/EdkBridgePkg.git
  - git clone --branch=development https://github.com/CupertinoNet/ApplePkg.git
  - git clone https://github.com/tianocore/edk2.git
  - cd edk2
  - make -C BaseTools
  - . edksetup.sh
  - cd $TRAVIS_BUILD_DIR

script:
  - . .travis/build.sh

notifications:
  irc:
    channels:
      - "irc.ext3.net#apple-efi"
    nick: TravisCi
    on_success: always
    on_failure: change
