language:
  - c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - clang-3.6
      - uuid-dev

before_install:
  - . .travis/before_install.sh

install:
  - . .travis/install.sh
  - cd $TRAVIS_BUILD_DIR/../
  - export PACKAGES_PATH=$PWD
  - git clone --branch=development https://github.com/CupertinoNet/EfiMiscPkg.git
  - git clone --branch=development https://github.com/CupertinoNet/EdkBridgePkg.git
  - git clone --branch=development https://github.com/CupertinoNet/ApplePkg.git
  - git clone https://github.com/tianocore/edk2.git
  - cd edk2/
  - make -C BaseTools/ -s
  - . edksetup.sh
  - cd $TRAVIS_BUILD_DIR/

script:
  - . .travis/build.sh

notifications:
  email: false 
  irc:
    channels:
      - "irc.ext3.net#apple-efi"
    nick: TravisCi
    on_success: always
    on_failure: change
